### ISSUE TITLE
Request: LuaJIT 

### ISSUE THREAD

**Issue by RHCPNG** [vwout/docker-openluup#7]
Hi vwout,

I'm back with another request. This is very interesting with respect to performance improvement. Can you please take a look at this post and consider implementing LuaJIT?

https://smarthome.community/topic/179/luajit/29?_=1606034453370

Looks promising. Always looking to improve my setup

**Comment by vwout** [comment]
Commit b1aef933024eaeabf265fd3bd3f491b0a2a4fbe4 adds LuaJIT (2.1.0-beta3) to the OpenLuup Docker images.
It is not used by default in the loader script (yet) and also does not replace Lua5.1 because that would break existing installation with a volume for `/etc/cmh-ludl/`.

To start using LuaJIT, modify `openLuup_reload_for_docker` and changes the lines `lua5.1 openLuup/init.lua $@` to `luajit openLuup/init.lua $@`

**Comment by RHCPNG** [comment]
Thanks for this! Can I just do the configuration with my current container without breaking things?

**Comment by vwout** [comment]
When you are using `/etc/cmh-ludl` as volume, your setting should be retained.
The file `openLuup_reload_for_docker` is in that volume, which means it is not changed or updated with a container update. To change it, you need to open a shell in the container. This can be done either before or after the update of the container since lua5.1 (non JIT) is also included.

Before changing the script, be sure to check that `luajit` indeed is available in the container. In case not (because your container updated failed), your container will result in a boot loop.

**Comment by RHCPNG** [comment]
Thanks, I will try it soon!
